import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Screen } from '@/components/screen';
import { request } from '@/lib/api';
import { colours, radius, spacing } from '@/lib/theme';
import { useApp } from '@/providers/app-provider';

type Earning = { id: string; title: string; amount_minor: number; earned_on: string; notes: string };
export default function EarningsScreen() {
  const { action } = useApp(); const [items, setItems] = useState<Earning[]>([]); const [title, setTitle] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const load = useCallback(async () => { const result = await request<{ earnings: Earning[] }>('?view=my'); setItems(result.earnings); }, []); useEffect(() => { void load(); }, [load]);
  const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.amount_minor), 0), [items]);
  async function add() { const amountMinor = Math.round(Number(amount) * 100); if (!title.trim() || !Number.isFinite(amountMinor) || amountMinor <= 0) return; try { await action({ action: 'earning', title, amountMinor, date, notes: '' }); setTitle(''); setAmount(''); await load(); } catch (problem) { Alert.alert('Could not add earning', problem instanceof Error ? problem.message : 'Please try again.'); } }
  return <Screen title="Earnings tracker"><View style={styles.total}><Text style={styles.totalLabel}>TOTAL RECORDED</Text><Text style={styles.totalValue}>{new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(total / 100)}</Text><Text style={styles.private}>Private to your account</Text></View><View style={styles.form}><Text style={styles.section}>Add earning</Text><TextInput value={title} onChangeText={setTitle} placeholder="What paid you?" placeholderTextColor={colours.slate} style={styles.input} /><TextInput value={amount} onChangeText={setAmount} placeholder="Amount in pounds" keyboardType="decimal-pad" placeholderTextColor={colours.slate} style={styles.input} /><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colours.slate} style={styles.input} /><Pressable onPress={() => void add()} style={styles.primary}><Text style={styles.primaryText}>Add earning</Text></Pressable></View><View style={styles.list}>{items.map((item) => <View key={item.id} style={styles.row}><View><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.earned_on}</Text></View><Text style={styles.amount}>{new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(item.amount_minor / 100)}</Text></View>)}</View></Screen>;
}
const styles = StyleSheet.create({ total: { padding: spacing.xl, borderRadius: radius.lg, backgroundColor: colours.navy, gap: 4 }, totalLabel: { color: colours.mint, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, totalValue: { color: 'white', fontSize: 36, fontWeight: '900' }, private: { color: '#C8D7E3', fontSize: 11 }, form: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colours.line, backgroundColor: colours.surface }, section: { color: colours.ink, fontSize: 17, fontWeight: '800' }, input: { height: 46, paddingHorizontal: 13, borderRadius: radius.md, borderWidth: 1, borderColor: '#C4D0D7', color: colours.ink, fontSize: 16 }, primary: { minHeight: 45, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colours.green }, primaryText: { color: 'white', fontWeight: '800' }, list: { gap: spacing.sm }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.lg, borderRadius: radius.md, borderWidth: 1, borderColor: colours.line, backgroundColor: colours.surface }, title: { color: colours.ink, fontWeight: '800' }, meta: { color: colours.slate, fontSize: 11, marginTop: 3 }, amount: { color: colours.green, fontSize: 16, fontWeight: '900' } });
