import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Screen } from '@/components/screen';
import { MessageState } from '@/components/states';
import { request } from '@/lib/api';
import { colours, radius, spacing } from '@/lib/theme';
import { age } from '@/lib/types';
import { useApp } from '@/providers/app-provider';

type Comment = { id: string; author: string; handle: string; body: string; parentId: string | null; createdAt: string; blockedByViewer: boolean; reactions: { reaction: string; count: number; mine: boolean }[] };

export default function CommentsScreen() {
  const { kind, id } = useLocalSearchParams<{ kind: string; id: string }>();
  const { signedIn, action } = useApp();
  const [comments, setComments] = useState<Comment[]>([]);
  const [body, setBody] = useState('');
  const [replyTo, setReplyTo] = useState<Comment | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await request<{ comments: Comment[] }>(`?view=comments&kind=${encodeURIComponent(kind)}&id=${encodeURIComponent(id)}`); setComments(result.comments); }, [id, kind]);
  useEffect(() => { void load(); }, [load]);

  async function submit() { if (!signedIn) { router.push('/login'); return; } setBusy(true); try { await action({ action: 'comment', kind, id, body, parentId: replyTo?.id ?? null }); setBody(''); setReplyTo(null); await load(); } catch (problem) { Alert.alert('Could not post', problem instanceof Error ? problem.message : 'Please try again.'); } finally { setBusy(false); } }
  return <Screen title="Discussion"><View style={styles.list}>{comments.map((comment) => <View key={comment.id} style={[styles.comment, comment.parentId && styles.reply]}>{comment.blockedByViewer ? <Text style={styles.blocked}>Comment from a blocked member</Text> : <><View style={styles.meta}><Text style={styles.author}>{comment.author}</Text><Text style={styles.time}>@{comment.handle} · {age(comment.createdAt)}</Text></View><Text style={styles.body}>{plain(comment.body)}</Text><View style={styles.actions}><Pressable onPress={() => setReplyTo(comment)}><Text style={styles.action}>Reply</Text></Pressable><Pressable onPress={() => void action({ action: 'react', kind, id: comment.id, reaction: 'helpful', selected: !comment.reactions.find((item) => item.reaction === 'helpful')?.mine }).then(load)}><Text style={styles.action}>👍 Helpful {comment.reactions.find((item) => item.reaction === 'helpful')?.count || ''}</Text></Pressable><Pressable onPress={() => Alert.alert('Report comment?', 'A moderator will review it.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Report', style: 'destructive', onPress: () => void action({ action: 'reportComment', kind, id: comment.id, reason: 'Reported from the iOS app.' }) }])}><Text style={styles.report}>Report</Text></Pressable></View></>}</View>)}</View>{!comments.length ? <MessageState title="No comments yet" body="Start a useful, respectful conversation." /> : null}<View style={styles.composer}>{replyTo ? <View style={styles.replying}><Text style={styles.replyingText}>Replying to @{replyTo.handle}</Text><Pressable onPress={() => setReplyTo(null)}><Text>×</Text></Pressable></View> : null}<TextInput multiline value={body} onChangeText={setBody} placeholder={signedIn ? 'Share your experience or ask a question…' : 'Sign in to join the discussion'} placeholderTextColor={colours.slate} editable={!busy} style={styles.input} /><Text style={styles.hint}>Type @ followed by a username to mention someone. Be kind and don’t share personal referral links.</Text><Pressable disabled={busy || body.trim().length < 2} onPress={() => void submit()} style={[styles.primary, (busy || body.trim().length < 2) && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Posting…' : signedIn ? 'Post comment' : 'Sign in to comment'}</Text></Pressable></View></Screen>;
}
function plain(body: string) { return body.replace(/!\[[^\]]*\]\([^)]*\)/g, '[Image]').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1').replace(/[*_\\]/g, '').trim(); }
const styles = StyleSheet.create({ list: { gap: spacing.md }, comment: { padding: spacing.lg, borderRadius: radius.md, backgroundColor: colours.surface, borderWidth: 1, borderColor: colours.line, gap: spacing.sm }, reply: { marginLeft: spacing.xl, borderLeftWidth: 3, borderLeftColor: colours.mint }, meta: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, author: { color: colours.ink, fontWeight: '800' }, time: { color: colours.slate, fontSize: 11 }, body: { color: colours.ink, fontSize: 14, lineHeight: 21 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.lg }, action: { color: colours.green, fontSize: 12, fontWeight: '700' }, report: { color: colours.slate, fontSize: 12 }, blocked: { color: colours.slate, fontStyle: 'italic' }, composer: { gap: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colours.surface, borderWidth: 1, borderColor: colours.line }, replying: { flexDirection: 'row', justifyContent: 'space-between', padding: spacing.sm, borderRadius: radius.sm, backgroundColor: colours.mintPale }, replyingText: { color: colours.green, fontSize: 12, fontWeight: '800' }, input: { minHeight: 120, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: '#C4D0D7', color: colours.ink, fontSize: 16, textAlignVertical: 'top' }, hint: { color: colours.slate, fontSize: 10, lineHeight: 15 }, primary: { minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colours.green }, primaryText: { color: 'white', fontWeight: '800' }, disabled: { opacity: 0.45 } });
